apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: helloworlds.release-exercise.sourcegraph.com
spec:
  group: release-exercise.sourcegraph.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            message:
              type: string

  # Namespaced b/c helloworld resources map to pods, and we need to decide to put the pod somewhere
  scope: Namespaced
  names:
    plural: helloworlds
    singular: helloworld
    kind: HelloWorld
