# permissions for end users to view helloworlds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: helloworld-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: release-exercise-sxlijin
    app.kubernetes.io/part-of: release-exercise-sxlijin
    app.kubernetes.io/managed-by: kustomize
  name: helloworld-viewer-role
rules:
  - apiGroups:
      - release-exercise.sourcegraph.com.release-exercise.sourcegraph.com
    resources:
      - helloworlds
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - release-exercise.sourcegraph.com.release-exercise.sourcegraph.com
    resources:
      - helloworlds/status
    verbs:
      - get
