---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  - apiGroups:
      - release-exercise.sourcegraph.com.release-exercise.sourcegraph.com
    resources:
      - helloworlds
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - release-exercise.sourcegraph.com.release-exercise.sourcegraph.com
    resources:
      - helloworlds/finalizers
    verbs:
      - update
  - apiGroups:
      - release-exercise.sourcegraph.com.release-exercise.sourcegraph.com
    resources:
      - helloworlds/status
    verbs:
      - get
      - patch
      - update
